# Generated by Django 3.0.3 on 2020-03-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': 'Post'},
        ),
    ]
